PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX sc: <http://iiif.io/api/presentation/2#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
CONSTRUCT {
?canvas rdf:type sc:Canvas .
?canvas sc:metadataLabels ?llist .
?lmid rdf:first ?label .
?label rdfs:label ?k .
?label rdf:value ?mvalue .
?lmid rdf:rest ?llast .
} WHERE {
?canvas sc:metadataLabels ?llist .
?llist rdf:rest* ?lmid .
?lmid rdf:first ?label .
?label rdfs:label ?k .
?label rdf:value ?mvalue .
?lmid rdf:rest ?llast .
}